import 'package:flutter/foundation.dart';
import 'package:myapp/services/user_service.dart';
import 'package:myapp/models/ServicesModel.dart';

class ServiceViewModel with ChangeNotifier {
  final UserService _userService = UserService();

  bool _isLoading = false;
  String? _error;
  List<Service> _userServices = [];

  bool get isLoading => _isLoading;
  String? get error => _error;
  List<Service> get userServices => _userServices;

  void _setLoading(bool loading) {
    _isLoading = loading;
    notifyListeners();
  }

  void _setError(String? error) {
    _error = error;
    notifyListeners();
  }

  // Create service using UserService
  Future<bool> createService(Service service) async {
    try {
      _setLoading(true);
      _setError(null);

      await _userService.addService(service);

      // Refresh services list
      await getServicesByProviderId(service.providerId);

      _setLoading(false);
      return true;
    } catch (e) {
      _setLoading(false);
      _setError('Failed to create service: $e');
      return false;
    }
  }

  // Create service with individual parameters
  Future<bool> createServiceFromData({
    required String providerId,
    required String title,
    required String description,
    required String category,
    required String subcategory,
    required double price,
    required String priceUnit,
    required String location,
    required double? latitude,
    required double? longitude,
    required List<String> tags,
    List<String> images = const [],
  }) async {
    try {
      _setLoading(true);
      _setError(null);

      final service = Service(
        id: '', // Will be generated by Firestore
        providerId: providerId,
        title: title,
        description: description,
        category: category,
        subcategory: subcategory,
        price: price,
        priceUnit: priceUnit,
        location: location,
        latitude: latitude,
        longitude: longitude,
        tags: tags,
        images: images,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 0.0,
        totalReviews: 0,
      );

      await _userService.addService(service);

      // Refresh services list
      await getServicesByProviderId(providerId);

      _setLoading(false);
      return true;
    } catch (e) {
      _setLoading(false);
      _setError('Failed to create service: $e');
      return false;
    }
  }

  // Get services by provider ID
  Future<List<Service>> getServicesByProviderId(String providerId) async {
    try {
      _setLoading(true);
      _setError(null);

      _userServices =
          (await _userService.getProviderServices(providerId)).cast<Service>();

      _setLoading(false);
      return _userServices;
    } catch (e) {
      _setLoading(false);
      _setError('Failed to fetch services: $e');
      _userServices = [];
      return [];
    }
  }

  // Update service
  Future<bool> updateService(Service service) async {
    try {
      _setLoading(true);
      _setError(null);

      await _userService.updateService(service);

      // Find and update local service
      final index = _userServices.indexWhere((s) => s.id == service.id);
      if (index != -1) {
        _userServices[index] = service;
      }

      _setLoading(false);
      return true;
    } catch (e) {
      _setLoading(false);
      _setError('Failed to update service: $e');
      return false;
    }
  }

  // Delete service
  Future<bool> deleteService(String serviceId, String userId) async {
    try {
      _setLoading(true);
      _setError(null);

      await _userService.deleteService(serviceId, userId);
      _userServices.removeWhere((service) => service.id == serviceId);

      _setLoading(false);
      return true;
    } catch (e) {
      _setLoading(false);
      _setError('Failed to delete service: $e');
      return false;
    }
  }

  void clearError() {
    _setError(null);
  }

  void clearServices() {
    _userServices = [];
    notifyListeners();
  }
}
